### ISSUE TITLE
Q: Should the icon be the asciidoctor icon rather than the 'A'?

### ISSUE THREAD

**Issue by snowolfe** [asciidoctor/asciidoctor-firefox-addon#16]
Trivial issue, but curious about your thoughts. I guess the other option is to be more generic and use the AsciiDoc logo (assuming they have one - I haven't seen it).

**Comment by ggrossetie** [comment]
New logo is here!!! 🎉 🎉 🎉 
We will do what the brand tell us: https://github.com/asciidoctor/brand

Closing since this change will be done in this repository: https://github.com/asciidoctor/asciidoctor-chrome-extension
