### ISSUE TITLE
Add configurable file extensions

### ISSUE THREAD

**Issue by snowolfe** [asciidoctor/asciidoctor-firefox-addon#17]
Enhancement request.

Can we add the ability to configure the file extensions that the the Add-on recognises, shipped with the current file extensions as default.

WDYT?

**Comment by ggrossetie** [comment]
Please open a new issue here: https://github.com/asciidoctor/asciidoctor-chrome-extension

As mentioned in #18 we could potentially use `<all_urls>` but we need to make sure that this does not affect performance too much.
