### ISSUE TITLE
Firefox add-on won't install on the phone

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-firefox-addon#25]
//cc @mojavelinux

**Comment by mojavelinux** [comment]
It's interesting that the desktop install doesn't seem to honor the range in the metadata. Maybe the mobile install is more strict?

**Comment by Mogztter** [comment]
The `cfx xpi` command is not using the `install.rdf` at the root of the repository, but generates a new one from the `package.json`.

Its turn out that the `cfx` tool is now deprecated in favor of `jpm`.

With `jpm` we can define an `engines` attribute in `package.json` to specify the target applications with min/max version.

I successfully install the add-on on my phone but... nothing happens when I'm browsing an .adoc file.

I will need to debug to find the cause of the issue. I found that some API are not supported in Fennec: https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Mobile_development#High-Level_APIs

First thing I need to do is to replace the `widget` API (I'm using the `widget` API to display the button in the toolbar).

**Comment by mojavelinux** [comment]
> With jpm we can define an engines attribute in package.json to specify the target applications with min/max version.

Excellent!

> I successfully install the add-on on my phone but... nothing happens when I'm browsing an .adoc file.

Same problem here. Let me know if you need help debugging.

**Comment by Mogztter** [comment]
Resolved by 027eea7a2a90b8f3446360c699aaaeaaa153d211

**Comment by mojavelinux** [comment]
:+1:
