### ISSUE TITLE
Add shortcut to allow raw-mode switching

### ISSUE THREAD

**Issue by valir** [asciidoctor/asciidoctor-firefox-addon#27]
As a vimperator user, using firefox only from my kbd, with all the visual whistles turned off (there is no toolbar visible on my setup), I'd really appreciate having a shortcut to switch to the raw-mode as right now I have no means to do it ;-)

**Comment by mojavelinux** [comment]
Good idea. I would definitely find that useful as well.

Do you know how an extension can add a keybinding to the viewport?

**Comment by ggrossetie** [comment]
Closing in favor of https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/186
