### ISSUE TITLE
Have options similar to the chrome extension

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/asciidoctor-firefox-addon#28]
being able to configure firefox addon similar to the chrome add on when it comes to custom attributes would be really useful.

See https://github.com/asciidoctor/asciidoctor.js/issues/114 for one example.

**Comment by Mogztter** [comment]
I know I need to give the Firefox extension some love :wink:

**Comment by mojavelinux** [comment]
:+1:

**Comment by Mogztter** [comment]
I really want to move from `cfx` to `jpm` but the prerequisites are:
 * Firefox version 34 or later to use an extension produced by jpm.
 * Firefox version 38 or later to use jpm (build tool).

https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_%28jpm%29

Do you think this is OK ?

**Comment by mojavelinux** [comment]
Absolutely. Firefox is pushing hard for upgrades and most of our users are pretty tech savvy, so I would expect them to be upgrading. Even Linux distribution have been good about upgrading the browser despite holding back versions of other programs.

**Comment by Mogztter** [comment]
Resolved by 4aa62a4a49d43c02c0d36b7ddec2466ac4e22427

**Comment by maxandersen** [comment]
build and Installed 0.4.0 and can verify this is there and working greatly now! thanks.
