### ISSUE TITLE
Configurable CSS

### ISSUE THREAD

**Issue by puce77** [asciidoctor/asciidoctor-firefox-addon#29]
Provide a way to configure a CSS to render the page. I guess it would make sense to specify this per site/ domain.

**Comment by Mogztter** [comment]
Hello @puce77 sorry for the late late reply. This is a very good idea.

**Comment by Mogztter** [comment]
@puce77 This feature is now available in the latest version: https://addons.mozilla.org/en-us/firefox/addon/asciidoctorjs-live-preview (you will need to open the options page to configure the stylesheet). For now you can only configure the stylesheet globally.

**Comment by ggrossetie** [comment]
Closing in favor of https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/185 since the Firefox and the Chrome extension had merged.
