### ISSUE TITLE
configurability "option/preferences" window for firefox addon

### ISSUE THREAD

**Issue by zaxebo1** [asciidoctor/asciidoctor-firefox-addon#32]
asciidoctor's chrome extension and opera extensions both have - **options , which can be configured/customised(theme, safe mode, ... and other options)**
but firefox extension for asciidoctor has no such customisability option

****

if you install "Copy Url Expert" firefox addon ( https://addons.mozilla.org/en-us/firefox/addon/copy-urls-expert/ ), then inside firefox it has its own "preferences" button to customize the "copy url expert" addon. So it is technically possible to have "preferences/options" window for customizing the individual firefox addon too , just like in chromium and opera

****

Hence, please add "preferences/options" in firefox addon of asciidoctor, so that one can customise the various options of firefox addon (like: theme, safe mode etc )

****

**(Priority Flag= This feature is not of much urgency. This may be taken care even after a long time  )**

**Comment by zaxebo1** [comment]
Screenshots

"Options" window to configure Chromium addon of asciidoctor
![a](https://cloud.githubusercontent.com/assets/4308927/8505261/fcd672bc-21fe-11e5-9172-5a90bedd46b6.png)

"preferences" button of "Copy url expert addon" in firefox. **Also see that there is no preferences button for asciidoctor addon in firefox**
![b](https://cloud.githubusercontent.com/assets/4308927/8505269/1d2f4570-21ff-11e5-9bd2-3cda98cb2725.png)

when we click "preferences" button of "Copy url expert" in firefox, we can get a full window to customise that addon. So it is technically possible to do so in firefox too
![c](https://cloud.githubusercontent.com/assets/4308927/8505275/4b0e8f96-21ff-11e5-998a-9cb28da5342c.png)

**Comment by mojavelinux** [comment]
I like that the Firefox Add-on system provides a native preferences system. We had to roll our own in the Chrome extension. Then again, it's pretty easy to create an HTML page whereas with the Firefox extension it might mean learning some XUL. :scream_cat: 

Btw, one of the reasons the Firefox addon lags behind in features is because Mozilla dragged their feet for a long time before accepting it. That's water over the dam. Now that it's been accepted, onward!

**Comment by zaxebo1** [comment]
:blush: 
okk

**Comment by Mogztter** [comment]
Related to #28

**Comment by Mogztter** [comment]
I want to avoid XUL as much as I can because... :scream_cat: 
Beside I think that Mozilla want to replace it ! 

A simple way is to use : https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-prefs
We just need to edit the `package.json` and use `require("sdk/simple-prefs").prefs;` API to retrieve the preferences... 

@zaxebo1 If you want to contribute this feature, I will be happy to review it :smile:

**Comment by zaxebo1** [comment]
**@Mogztter said:**

````
@zaxebo1 If you want to contribute this feature, I will be happy to review it :smile: 
````

**my reply** :

being a researcher, **i do not have much of web "development" skills** . But because i have just a week back tentatively switched from "sphinx and org-mode" to "asciidoctor", i am getting used to it around its rough edges. 

Then i need to learn ruby. May be six months later, if i am still using asciidoctor, then i will start contributing to asciidoctor.

****

I think **my potential contribution to asciidoctor(after six months from now) can be, one of these** :

 1) contributing to the "asciidoctor-latex backend". This backend is not outputting the 
     potential roadblock: the "backend architecture" section of user-manual ( http://asciidoctor.org/docs/user-manual/#custom-backends ) is right now empty. Probably once that section is documented, it will give me enough ropeway to start tinkering with existing 
 
 OR 2) "funding" the "asciidoctor to sphinx generation backend". I can fund a humble amount of USD 100 , for somebody who wants to take this up. The test case will be , if user-manual of asciidoctor is converted to sphinx format, and uploaded to readthedocs.org, then i will pay him up. 
 advantage: if tomorrow asciidoctor project dies, then i can just convert myself to sphinx and can continue easily.Also sphinx gives many more output formats. 
  This project, i do not want to take up personally, i would like that somebody creates it and i fund it .
   
 OR 3) i may contribute some asciidoctor extensions
 
 OR 4) i may take up the vim-asciidoctor support to the level of emacs-orgmode. There are lots of lacunas and scope in this. Org-mode is awesome. 
 
 May be point#4 is most close to my heart, so this is more likely. Many researchers are working still with vim/emacs, the asciidocotr support is very infant compared to org-mode conveniences.

***
 
**But this is for sure, that if i am able to continue my current steam of interest in asciidoctor for six months, i will definitely contribute back.**
 
But before that, **during these six months - i will continue to to bug you people with small issues/suggestions of mine :-( , as coming from sphinx/org-mode".**

**Comment by Mogztter** [comment]
@zaxebo1 That's fine, I was asking because I think that this issue can be a good candidate for a first contribution

> i may take up the vim-asciidoctor support to the level of emacs-orgmode. 

Oh oh, I look forward to it, I'm also a vim user :smile:
