### ISSUE TITLE
Table of Contents not being generated

### ISSUE THREAD

**Issue by jeffcpullen** [asciidoctor/asciidoctor-firefox-addon#38]
Adding :toc: to the top of the document is not generating the table of contents as expected.

**Comment by Mogztter** [comment]
Hi @jeffcpullen, you need to add a toc placement `:toc: preamble`, see : https://github.com/asciidoctor/asciidoctor-chrome-extension#toc

Asciidoctor 1.5.3 will make things easier: https://github.com/asciidoctor/asciidoctor/issues/1443

**Comment by jeffcpullen** [comment]
@Mogztter thanks for the quick feedback. I see that you've referenced the chrome extension, but the only browser available in this environment is Firefox. Neither of the suggested formats in the chrome-extension docs worked for the Firefox addon. I've included examples of the first few lines of my file just to sanity check that it isn't just user error. 

Both of these fail to generate ToC
= Title
:toc:
:toc-placement!:
toc::[]

and 

= Title
:toc: preamble

**Comment by jeffcpullen** [comment]
Closing. This was NOT a bug but user error. Thanks for your help @Mogztter

**Comment by Mogztter** [comment]
> I see that you've referenced the chrome extension, but the only browser available in this environment is Firefox.

The documentation is more up to date on the Chrome extension but toc placement are working in both Chrome and Firefox (and also Opera because they are all using Asciidoctor.js 1.5.2).

> Both of these fail to generate ToC

Can you confirm that both your examples are working ?
Thanks :smile:

**Comment by jeffcpullen** [comment]
Tested on Firefox 38 and both ways work.

The elements of the ToC act as if they are clickable but don't jump to the section. Assuming this is expected behavior.

**Comment by Mogztter** [comment]
Ok.
I think you need to add `:sectanchors:` to add anchors on section title.

**Comment by mojavelinux** [comment]
Actually, I see that same behavior. It appears that something is removing the href attribute from the links in the toc. Could this be the sanitizer?

**Comment by mojavelinux** [comment]
All internal links (cross references) suffer from this problem. It's not just limited to the toc. Perhaps open a new issue to track?

**Comment by Mogztter** [comment]
Yes you're right, this is related to #31. Links are striped away for "security" reason...
