### ISSUE TITLE
URI with parameter does not render...

### ISSUE THREAD

**Issue by cschanck** [asciidoctor/asciidoctor-firefox-addon#40]
For example: something like this:

http://<stuff>/adoc.adoc?at=436e9bd2b3ec2b83b704f35c898275a35367111a&raw

It fails to notice it is asciidoc with a parm. Sadface.

Works great on Chrome, but Firefox fails.

**Comment by cschanck** [comment]
I had left a review to this effect, but deleted it in favor of an issue here.

**Comment by Mogztter** [comment]
Hi @cschanck, thanks for your report.
Indeed the current regular expression is too restrictive: https://github.com/asciidoctor/asciidoctor-firefox-addon/blob/master/data/asciidocify.js#L8

I will update the code to have the same behavior as the Chrome Extension.

**Comment by mojavelinux** [comment]
> I will update the code to have the same behavior as the Chrome Extension.

:+1: 

I had noticed this as well. I'm looking forward to it!

**Comment by cschanck** [comment]
Excellent, excellent!

**Comment by mojavelinux** [comment]
:+1:
