### ISSUE TITLE
Writing in forms and convert it to markdown, HTML or bbcode

### ISSUE THREAD

**Issue by timofonic** [asciidoctor/asciidoctor-firefox-addon#44]
Hello.

This addon seems quite interesting, but it doesn't solve a personal issue.
- I often write on forums and markdown-only places. I even get obsessed with formatting.
- They usually use bbcode or HTML. I hate to write in that bloated and confusing syntax.
  - I would love to write it in AsciiDoc, preview it and click one of three options: markdown, bbcode, html.
  - It would be amazing if this would be compatible with Google WebApps: Gmail, Docs/Drive.

Kind regards.

**Comment by Mogztter** [comment]
Hello @timofonic,

> I would love to write it in AsciiDoc, preview it and click one of three options: markdown, bbcode, html.

With Asciidoctor you can create a new backend to customize the generated output. So technically you can produce Markdown, bbcode and "simplified" HTML with Asciidoctor.

To write a new backend you can have a look at this repository: https://github.com/asciidoctor/asciidoctor-backends

Once the backend written I could easily add an option to choose the output format.

> It would be amazing if this would be compatible with Google WebApps: Gmail, Docs/Drive.

I wrote an Add-on for Google Drive to export from Google Drive to AsciiDoc: https://github.com/Mogztter/asciidoc-googledocs-addon

**Comment by Mogztter** [comment]
Closing, the new repository is: https://github.com/asciidoctor/asciidoctor-chrome-extension
