### ISSUE TITLE
Giving up on AMO

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-firefox-addon#46]
I'm seriously considering giving up on AMO.
I mean, the current user experience is terrible, the validation process takes ages and ultimately, this slow down the development process. I'm too scared to add features because of AMO. 

Chrome extension has live reload, custom stylesheets, emoji, Font Awesome... Firefox Addon can render only simple AsciiDoc document. This is absurd.

@mojavelinux What do you think ?

Releases will be available as "signed" (hopefully) xpi files on GitHub: https://github.com/asciidoctor/asciidoctor-firefox-addon/releases

**Comment by mojavelinux** [comment]
I'm 100% in favor of this decision. I'd rather move forward than to waste time getting blessing from Mozilla. I'd even be in favor of pulling the listing from AMO and promoting our own releases. We know our users and they know us. We certainly don't need Mozilla's registry. Let's break free.

**Comment by Mogztter** [comment]
:+1: :smile: 
Let's move forward!

**Comment by Mogztter** [comment]
Great signing API is broken: https://bugzilla.mozilla.org/show_bug.cgi?id=1244644 and only advanced user can install unsigned extension: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u

Looks like we don't have a choice...

**Comment by mojavelinux** [comment]
I was able to install it without any trouble. Sure, it displays a warning, but I just ignore that as normal browser whining. We could, of course, explain the situation in the README.

**Comment by mojavelinux** [comment]
I think people prefer function over getting rid of warning messages.

**Comment by Mogztter** [comment]
I think we can this issue because we now have a [self-hosted signed version](https://github.com/asciidoctor/asciidoctor-firefox-addon/releases/tag/v0.5.3) :tada:

**Comment by mojavelinux** [comment]
Great work @Mogztter!

**Comment by Mogztter** [comment]
Are you kidding me ?! AMO review version 0.5.1 in less than a week and they didn't force me to sanitize the output! Wow!

https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview

**Comment by mojavelinux** [comment]
That's what we call lighting a fire under someone's backside.
