### ISSUE TITLE
Sintax highlighting doesn’t fully work

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor-firefox-addon#49]
I set source-highlighter=highlightjs in the options.
I get 

```
<pre class="highlightjs highlight"><code class="language-xml" data-lang="xml">&lt;entry&gt;
  &lt;address&gt;&lt;/address&gt;
  &lt;name&gt;&lt;/name&gt;
&lt;/entry&gt;</code></pre>
```

So it seems that it only escapes the lt/gt, but nothing more (I don’t get any coloring)

**Comment by Mogztter** [comment]
Thanks for your report @andya9 I will have a look. Are you using the latest release 0.5.0 ?

**Comment by andya9** [comment]
No, I’m still on 0.4. But it seems its a problem with asciidoctor itself, I’ll open an issue there and close here

**Comment by Mogztter** [comment]
I guess this is fixed now... closing! Feel free to reopen this issue.
