### ISSUE TITLE
:toc setting in AsciiDoc ignored

### ISSUE THREAD

**Issue by pondrejk** [asciidoctor/asciidoctor-firefox-addon#50]
I'm not able to build html with table of contents, tried

```
:toc:
```

and

```
:toc: right
```

Local build with asciidoctor cli tool works all right with the same file.

**Comment by Mogztter** [comment]
Hey @pondrejk ,

the Firefox addon converts the document to embeddable HTML (header and footer disabled), the only TOC placement that work are preamble (if the document has a preamble) or manual placement.

Here's a working example with version 0.4.0:

```
= Test
:toc: preamble

This is a preamble

== Title 1

== Title 2
```

![firefox-toc](https://cloud.githubusercontent.com/assets/333276/13053573/7f83514a-d405-11e5-8216-955659d72e4d.png)

**Comment by pondrejk** [comment]
Thanks @Mogztter ,

The cause is probably in the structure of my document, the asciidoc I open is just a list of includes that pulls individual sections from separate files. What you suggest above works in those documents with actual content, but not in the top-level includes file. Feel free to close the issue if this is expected behavior.

**Comment by mojavelinux** [comment]
You probably need to set the safe mode to "safe" on the settings page.
