### ISSUE TITLE
RFE: passing custom asciidoctor attributes to the addon

### ISSUE THREAD

**Issue by pondrejk** [asciidoctor/asciidoctor-firefox-addon#51]
I'd like to have a way to specify custom options for asciidoctor build without modifying the actual file, something similar to the `asciidoctor -a` option.

**Comment by pondrejk** [comment]
Just found #37 and https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/master/README.adoc#toc but no luck with `:toc: preamble` either.

**Comment by Mogztter** [comment]
You can pass custom attributes from the preferences page:

![firefox-addon-prefs](https://cloud.githubusercontent.com/assets/333276/13053608/a7d3dbc4-d405-11e5-997e-b9ef736671ca.png)

Let me know if this is working for you.

Related issues (now resolved): #28 and #32

**Comment by pondrejk** [comment]
Cool, didn't notice that. Cheers!
