### ISSUE TITLE
Q: How to use addon in firefox mobile

### ISSUE THREAD

**Issue by mgrafl** [asciidoctor/asciidoctor-firefox-addon#52]
Hi, 

I have installed the addon in Firefox Mobile on Android. How can I get it working? 
The 'A' icon is not shown and neither remote nor local .adoc files are rendered. 
I already tried rebooting the phone, but without luck. 

I would be glad for any suggestions for enabling asciidoctor rendering. 

Thanks, Michael

**Comment by Mogztter** [comment]
Hello @mgrafl, I can confirm that the latest version doesn't work with Firefox Mobile. I think this is related to the options/preferences addition.

I will do some more testing to find and fix the root cause. In the meantime, you can download and use version 0.3.2: https://github.com/asciidoctor/asciidoctor-firefox-addon/releases/tag/v0.3.2

**Comment by mgrafl** [comment]
Thanks, Version 0.3.2 works for remote content. 

Is there a way to render also local content from "file://..."? 

Best regards, Michael

**Comment by Mogztter** [comment]
Never tried, do you have an error message or something ?

**Comment by Mogztter** [comment]
Could you please try https://github.com/asciidoctor/asciidoctor-firefox-addon/releases/tag/v0.5.4 ?

**Comment by Mogztter** [comment]
@mgrafl you are right local content does not work but I don't know exactly why. I will need to do remote debug. For those who are wondering, you can type `file:///mnt/sdcard/` in Firefox Mobile and then browse local files.

**Comment by mgrafl** [comment]
Version 0.5.4 works fine for remote content, thanks. 

For local content, I did not get any error messages, the content is simply not rendered. In the desktop version of the Google Chrome addon, a special permission is required for processing local files. Maybe it's a similar issue in Firefox? 

Best regards, Michael

**Comment by Mogztter** [comment]
> In the desktop version of the Google Chrome addon, a special permission is required for processing local files. Maybe it's a similar issue in Firefox?

Maybe, I will try to find some documentation about Firefox Mobile.
