### ISSUE TITLE
new API for firefox extension is released

### ISSUE THREAD

**Issue by zaxebo1** [asciidoctor/asciidoctor-firefox-addon#54]
firefox old API for extensions will deprecated in future. 
Details of new API for mozilla firefox have started to emerge. please see:

http://phoronix.com/scan.php?page=news_item&px=WebExtensions-Firefox-48
https://blog.mozilla.org/addons/2016/04/29/webextensions-in-firefox-48/
https://github.com/mdn/webextensions-examples
https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**In longer run**, this asciidoctor extension for firefox will have to be ported to new API . This request is not needed just now,  but in long run please keep it in plan

**Comment by zaxebo1** [comment]
the best part of the new API is:

>The technology is designed for cross-browser compatibility: to a large extent the API is compatible with the extension API supported by Google Chrome and Opera. Extensions written for these browsers will in most cases run in Firefox with just a few changes. The API is also fully compatible with multiprocess Firefox.

source: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by Mogztter** [comment]
Hi @zaxebo1 Yes it's planned!
Depending on how well this API is implemented and supported we might be able to have one code base for Chrome, Opera, Firefox and Edge. This is exciting because all features available on Chrome could be available for Firefox and Edge :smiley:

**Comment by zaxebo1** [comment]
Thanks :smile: 
as it is already  in plan/roadmap, then you may close this issue

**Comment by Mogztter** [comment]
@mojavelinux Maybe it's time to focus the development on [WebExtensions ](https://github.com/Mogztter/asciidoctor-webextensions) and release a single extension for Chrome, Opera and Firefox (based on WebExtensions API) ?

If we want to smooth the transition (and keep the Git history) we could remove specific code from the Chrome Extension repository. Then we could publish a new version of the extension to make sure that everything is working fine on Chrome, then publish this version on Firefox 45+.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by mojavelinux** [comment]
That sounds like a great plan to me!

**Comment by Mogztter** [comment]
@zaxebo1 The latest version available on the Firefox Add-ons website is now based on WebExtensions API: https://addons.mozilla.org/en-us/firefox/addon/asciidoctorjs-live-preview :tada:

**Comment by zaxebo1** [comment]
Trillions of thanks  :-)
