### ISSUE TITLE
MathJax not supported

### ISSUE THREAD

**Issue by hsanson** [asciidoctor/asciidoctor-firefox-addon#55]
The :stem: option to support math equations in files is not supported. The equations show as ascii instead of using MathJax.

**Comment by Mogztter** [comment]
@hsanson Could you please install the latest version: https://addons.mozilla.org/en-us/firefox/addon/asciidoctorjs-live-preview
This feature should be available since the Chrome and Firefox extension had merged.

**Comment by hsanson** [comment]
Seems to work... the equations get render but the layout needs some work. Since that is a different issue I will close this one.

![screenshot_20171030_085837](https://user-images.githubusercontent.com/900716/32150076-04c13c56-bd51-11e7-9b90-ec8dc083c0df.png)

**Comment by Mogztter** [comment]
Indeed could you please share a sample document so I can reproduce this
issue ? Thanks 😊

Le 30 oct. 2017 1:03 AM, "Horacio Sanson" <notifications@github.com> a
écrit :

**Comment by hsanson** [comment]
@Mogztter it is now rendering correctly after I restarted firefox so I would say the issue is solved.

**Comment by Mogztter** [comment]
Ok, let me know if you can reproduce this issue.
