### ISSUE TITLE
Support for asciidoctor diagram

### ISSUE THREAD

**Issue by hsanson** [asciidoctor/asciidoctor-firefox-addon#56]
There is no support for asciidoctor diagram. 

  http://asciidoctor.org/docs/asciidoctor-diagram/

**Comment by mojavelinux** [comment]
This is true of all Asciidoctor.js-based tools (Chrome extension, Firefox add-on, Atom plugin, etc). Asciidoctor Diagram does not work in the Asciidoctor.js environment yet.

We've discussed possible ways to make this happen, such as using a web service. However, that's likely something we'll do in a separate extension that we use in the Asciidoctor.js environment.

Note that Asciidoctor Diagram does have a web service component that we could use for this. See https://github.com/asciidoctor/asciidoctor.js/issues/84#issuecomment-65519602

**Comment by ggrossetie** [comment]
Since the Firefox and the Chrome extension had merged, we can continue the discussion here: https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/79
