### ISSUE TITLE
Q. ifdef directive?

### ISSUE THREAD

**Issue by junaruga** [asciidoctor/asciidoctor-firefox-addon#57]
Does the addon handle the feature to display the content in ifdef directive?
http://asciidoctor.org/docs/user-manual/#ifdef-directive

Thanks.

**Comment by Mogztter** [comment]
Hello @junaruga 
Yes `ifdef` directive is working:

```
= Test
:env-github:

ifdef::env-github[]
This content is for GitHub only.
endif::[]
```

![test](https://cloud.githubusercontent.com/assets/333276/15552087/3f1c48de-22b9-11e6-9933-d57b2c151eaa.PNG)

**Comment by junaruga** [comment]
Thank you for the message and quick replying!
I am happy for that.

On your case, could you tell me how to set env-github attribute?
I would like to see the html converted with specified attribute on the addon.

Below is in the case of asciidoctor command. I want to do this kind of thing on the addon.
Is there setting page on the addon? I could not find it.

```
asciidoctor -a some_attribute Something.adoc
```

Thanks.

**Comment by Mogztter** [comment]
Yes you can!

Go to `about:addons`

![attr](https://cloud.githubusercontent.com/assets/333276/15585052/d2d623d2-237d-11e6-9165-5c671e74a73b.PNG)

In custom attributes field you can defined attributes.

**Comment by mojavelinux** [comment]
Am I correct that the Firefox add-on also supports setting attributes from the query string? (or is that still pending?)

**Comment by Mogztter** [comment]
This feature is only available in the Chrome extension: https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/master/app/js/renderer.js#L99

I think we need to open an issue here to track progress

**Comment by mojavelinux** [comment]
See #58.

**Comment by junaruga** [comment]
@Mogztter thank you!
I could see the content in ```ifdef```  directive, finally!

**Comment by junaruga** [comment]
Sorry, let me reopen this page.

Could you tell me how to display ```ifdef``` as inline element?


I tried to display ascii doc on the addon.

- "Something1" was displayed.
- "Something2" was not displayed. the ```ifdef``` was not recognized.
- "Something3-1" was displayed and the ```ifdef``` was recognized. But the result is "This is Something3-1[1 space]." This result is not my ideal one.

Actually I want to use  ```ifdef::env-github[Something1]``` as inline element, not block element.

```
= Test
:env-github:

ifdef::env-github[Something1]

This is ifdef::env-github[Something2].

This is
ifdef::env-github[Something3-1]
ifdef::env-another[Something3-2]
.
```
That means for example, I want to display below case as "This is Something2."

```
This is ifdef::env-github[Something2]ifdef::foo[Something2-1]ifdef::foo[Something2-2].
```

Is this a specification of Ascii Doc, or bug?

asciidoctor also had same result with the addon.
```
$ asciidoctor -a env-github mytest/test.adoc
```

Thank you.

**Comment by mojavelinux** [comment]
A preprocessor directive must be on a line by itself. That's a rule in
AsciiDoc.

**Comment by junaruga** [comment]
@mojavelinux thank you for the quick response. I understood it.
