### ISSUE TITLE
Allow AsciiDoc attributes to be defined using the query string

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-firefox-addon#58]
Allow AsciiDoc attributes to be defined using the query string. These attributes take precedence over attributes defined in the document (unless the value ends in `@`, a condition which is handled by the processor).

This feature is already implemented in the Chrome extension. See https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/99 for reference.

**Comment by Mogztter** [comment]
Since the Firefox and the Chrome extension had merged, I'm closing this issue.
This feature is available in the "Chrome/Browser" extension, please install the latest version: https://addons.mozilla.org/en-us/firefox/addon/asciidoctorjs-live-preview
