### ISSUE TITLE
Publish on AMO

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-firefox-addon#9]

**Comment by Mogztter** [comment]
@mojavelinux "5 months in the queue" https://forums.mozilla.org/viewtopic.php?f=21&t=22584

**Comment by mojavelinux** [comment]
When I read that response, I feel a lot of a pain. But at least it ends on a promising note.

> Thanks for the feedback. We'll try to get to your add-on soon, so please be patient.

We can be grateful for something, I suppose ;)

**Comment by Mogztter** [comment]
And done! :tada: https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/

**Comment by mojavelinux** [comment]
:beers: and lots of them! Congrats!
